languageCode = 'en-uk'
title = 'G10 OER'
theme = 'hugo-theme-relearn'
[params]
    alwaysopen = true
    collapsibleMenu=true
    ordersectionsby = 'title'
    [[params.themeVariant]]
        auto = []
        identifier = 'relearn-auto'
        name = 'Auto switch theme'

    [[params.themeVariant]]
        identifier = 'relearn-light'
        name = 'Light'

    [[params.themeVariant]]
        identifier = 'relearn-dark'
        name = 'Dark'

[menu]
  [[menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-github"></i> '
    name = 'GitHub Repo'
    url = 'https://github.com/gektec/G10'
    weight = 1

  [[menu.shortcuts]]
    name = 'Merlot'
    url = 'https://merlot.org/merlot/viewMaterial.htm?id=773474103'
    weight = 2

  [[menu.shortcuts]]
    name = '2023 Group8 OER'
    url = 'https://www.merlot.org/merlot/viewSite.htm?id=9166460'
    weight = 3
    